"""migrate_1

Revision ID: 5291e2463648
Revises: 
Create Date: 2024-02-05 01:12:02.024637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5291e2463648'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('about_me', sa.String(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('experience',
                    sa.Column('year_start', sa.Integer(), nullable=False),
                    sa.Column('year_finish', sa.Integer(), nullable=False),
                    sa.Column('company', sa.String(), nullable=False),
                    sa.Column('job', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('user_fk', sa.Integer(), nullable=False),
                    sa.Column('published', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(['user_fk'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('skills',
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('img', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('user_fk', sa.Integer(), nullable=False),
                    sa.Column('published', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(['user_fk'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills')
    op.drop_table('experience')
    op.drop_table('users')
    # ### end Alembic commands ###
